name: Update README.md with Changed Files

on:
  push:
    branches:
      - '**'  # Запускается при любом пуше в любую ветку

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Гарантирует, что у нас есть предыдущий коммит для сравнения

      - name: Get the list of changed files
        id: changed-files
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt

      - name: Prepare new README section
        run: |
          echo -e "<!-- CHANGED_FILES_START -->\n## Changed Files in the Last Commit\n" > new_section.txt
          while read line; do echo "- $line"; done < changed_files.txt >> new_section.txt
          echo -e "\n<!-- CHANGED_FILES_END -->" >> new_section.txt

      - name: Update README.md
        run: |
          sed -i '/<!-- CHANGED_FILES_START -->/,/<!-- CHANGED_FILES_END -->/c\<-- CHANGED_FILES_START -->\n## Changed Files in the Last Commit\n' README.md
          sed -i '/<!-- CHANGED_FILES_START -->/r new_section.txt' README.md

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Updated README.md with list of changed files'
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
